version: "3.8"

services:
  producer:
    build:
      context: ./app/
      dockerfile: Dockerfile-producer
    container_name: producer
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - postgres
    env_file:
      - ./app/.env
    networks:
      - app_network

  postgres:
    image: postgres:14.1-alpine
    restart: always
    container_name: postgres
    env_file:
      - ./app/.env
    ports:
      - "5432:5432"
    networks:
      - app_network

  consumer:
    build:
      context: ./consumer/
      dockerfile: Dockerfile-consumer
    container_name: consumer
    depends_on:
      - rabbitmq
    env_file:
      - ./consumer/.env
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ./.env
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
