version: "3.8"

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile-producer
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - db
    env_file:
      - ./.env
#    environment:
#      - RABBITMQ_URL=amqp://guest:guest@rabbitmq/
    networks:
      - app_network

  consumer:
    build:
      context: .
      dockerfile: Dockerfile-consumer
    container_name: email_consumer
    depends_on:
      - rabbitmq
    env_file:
      - ./.env
#    environment:
#      - RABBITMQ_URL=amqp://guest:guest@rabbitmq/
#      - SMTP_SERVER=sandbox.smtp.mailtrap.io
#      - SMTP_PORT=587
#      - SMTP_USERNAME=14db251f6060e2
#      - SMTP_PASSWORD=5f6f0551c4af30
    networks:
      - app_network

  db:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - ./.env
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ./.env
#    environment:
#      RABBITMQ_DEFAULT_USER: guest
#      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
